### Implement any 10 functionalities using numpy values.

In [1]:
import numpy as np
 
arr = np.array([1, 2, 3])
print("1D Array: \n",arr)
 
arr = np.array([[1, 2, 3],
                [4, 5, 6]])
print("\n2D Array: \n", arr)

1D Array: 
 [1 2 3]

2D Array: 
 [[1 2 3]
 [4 5 6]]


In [2]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print("Original array: \n", arr)
print("\nSliced array: \n", arr[1:8:2])

Original array: 
 [ 1  2  3  4  5  6  7  8  9 10]

Sliced array: 
 [2 4 6 8]


In [3]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5, 6],[ 7, 8, 9, 10, 11, 12]])
print("Array: \n", arr)
print("\nShape of an array: \n", arr.shape)

Array: 
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]

Shape of an array: 
 (2, 6)


In [4]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(4, 3)
print("Original array: \n", arr)
print("\nReshaped array: \n", newarr)

Original array: 
 [ 1  2  3  4  5  6  7  8  9 10 11 12]

Reshaped array: 
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [11]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])
for x in arr:
  print("element:", x)

element: [1 2 3]
element: [4 5 6]


In [6]:
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
print("Array 1: \n", arr1)
print("\nArray 2: \n", arr2)

arr = np.concatenate((arr1, arr2))
print("\nJoined Array: \n", arr)

Array 1: 
 [1 2 3]

Array 2: 
 [4 5 6]

Joined Array: 
 [1 2 3 4 5 6]


In [3]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])
print("Original Array: \n", arr)

newarr = np.array_split(arr, 3)
print("\nSplitted Array: \n", newarr)

Original Array: 
 [1 2 3 4 5 6]

Splitted Array: 
 [array([1, 2]), array([3, 4]), array([5, 6])]


In [8]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 4, 4])
x = np.where(arr == 4)

print("Indexes of searched element: ", x)

Indexes of searched element:  (array([3, 5, 6]),)


In [9]:
import numpy as np

arr = np.array([3, 2, 0, 1])
print("Original Array: \n", arr)
print("\nSorted Array: \n", np.sort(arr))

Original Array: 
 [3 2 0 1]

Sorted Array: 
 [0 1 2 3]


In [10]:
import numpy as np

arr = np.array([41, 42, 43, 44])
x = [True, False, True, False]
print("Original array: \n", arr)

newarr = arr[x]
print("\nFiltered array: \n", newarr)

Original array: 
 [41 42 43 44]

Filtered array: 
 [41 43]
